import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./globals.media.css";
import Footer from "./_components/Footer";
import { Toaster } from "react-hot-toast";
import Navbar from "./_components/Navbar/Navbar_";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: `(prefers-color-scheme: dark)`,
        url: `/logo-dark.svg`,
        href: `/logo-dark.svg`,
      },
      {
        media: `(prefers-color-scheme: light)`,
        url: `/logo-light.svg`,
        href: `/logo-light.svg`,
      },
    ]
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ThemeProvider>
          <Navbar />
          <main>
            {children}

            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  background: '#888',
                  color: '#fff',
                  padding: "1rem 3rem",
                  boxShadow: "2px 2px 4px rgba(0,0,0,0.5)",
                },
                success: {
                  duration: 2000,
                  style: {
                    background: '#5a5',
                    border: '2px solid green',
                  },
                },
                error: {
                  duration: 4000,
                  style: {
                    background: '#a55',
                    border: '2px solid darkred',
                  },
                },
                custom: {
                  duration: 36000,
                }
              }}
            />

          </main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
